### ISSUE TITLE
Not getting detected object boxes to render in PSI Studio

### ISSUE THREAD

**Issue by kahlilfitz** [microsoft/psi-samples#10]
Using the WhatsThat example, I am able to write a <List<Tuple<System.Drawing.Rectangle, string>>> to the store. I am expecting to be able to drag and drop this on top of an image to overlay detected objects and their name. I'm following along with the example but the PSI Studio is not rendering the boxes.

here's a [link](https://github.com/kahlilfitz/realsense-psi-demo) to the code.

**Comment by danbohus** [comment]
Can you describe a bit more what exactly happens when you drag the stream over an existing panel (that I assume already contains the image visualization)? 

If a new visualization object gets created (and appears under the tree in the Layout tab), have you changed the Height and Width properties of the newly created visualization object?

Finally, you can trying verifying that the object detection is indeed actually generating results...  A couple of ways to check would be: right click on the list-of-tuple stream and select "Visualize messages in new panel" and you should see where there are messages on that stream. Alternatively, you could also change the code to print some of the info to console to make sure the object detection is running correctly and generating results.

**Comment by kahlilfitz** [comment]
I have verified that the messages are present and changed the panel width to be the width of the image.  The dataset will not drag into the visualization panel at all.  I've attached a screenshot of the dataset properties:
![PSIDetectedObjects](https://user-images.githubusercontent.com/4228307/96623108-b59dc000-12bf-11eb-87f5-1b4096974b99.png)

**Comment by chitsaw** [comment]
I think this issue is related to an assembly name mismatch between .NET Core and .NET Framework types for System.Drawing.Rectangle. As a workaround, could you modify your RealSenseDemo project to target net472 instead of netcoreapp3.1?

**Comment by kahlilfitz** [comment]
After a little work to migrate the project, that did the trick!
![PSIStudio](https://user-images.githubusercontent.com/4228307/97010511-5b3c7380-14fa-11eb-803f-b31700965e98.png)
